include: package:very_good_analysis/analysis_options.yaml
analyzer:
    errors:
        use_super_parameters: ignore
formatter:
    page_width: 106
linter:
    rules:
        always_use_package_imports: false
        avoid_catches_without_on_clauses: false
        avoid_equals_and_hash_code_on_mutable_classes: false
        avoid_final_parameters: false
        avoid_function_literals_in_foreach_calls: false
        avoid_multiple_declarations_per_line: false
        avoid_positional_boolean_parameters: false
        avoid_types_on_closure_parameters: false
        curly_braces_in_flow_control_structures: false
        document_ignores: false
        lines_longer_than_80_chars: false
        matching_super_parameters: true
        no_literal_bool_comparisons: true
        omit_obvious_local_variable_types: true
        omit_obvious_property_types: true
        parameter_assignments: false
        prefer_expression_function_bodies: true
        prefer_final_parameters: true
        prefer_foreach: true
        prefer_mixin: true
        prefer_relative_imports: true
        public_member_api_docs: false
        require_trailing_commas: true
        specify_nonobvious_property_types: false
        strict_top_level_inference: false
        type_annotate_public_apis: false
        unnecessary_null_aware_operator_on_extension_on_nullable: true
        use_truncating_division: true