name: nga_sdk
description: "NGA SDK is an auxiliary SDK for Android(and Flutter for Android) development, aiming to provide a better development experience for NGAs."
version: 3.6.0
repository: https://gitcode.com/OutOfMemories-WorkGroup/NGA-SDK
environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  vector_graphics: ^1.1.18
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  fonts:
    - family: BOOT
      fonts:
        - asset: nga_dat/boot.ttf
  assets: 
    - nga_dat/arrow_forward.vec